// frontend/src/app/features/cases/list/case-list.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  signal,
  viewChild,
} from '@angular/core';
import { Router } from '@angular/router';
import { SdButton } from '@sdcorejs/angular/components/button';
import { SdSection } from '@sdcorejs/angular/components/section';
import { SdTable, type SdTableOption } from '@sdcorejs/angular/components/table';
import { SdInput } from '@sdcorejs/angular/forms/input';
import { SdPageComponent } from '@sdcorejs/angular/modules/layout';
import type { CaseSummary } from '../../../core/api/models';
import { StartFlowApiService } from '../../../core/api/startflow-api.service';
import { CoreFormAccessibilityDirective } from '../../../shared/a11y/core-form-accessibility.directive';
import { formatCurrency, formatDateTime } from '../../../shared/formatters';
import { EmptyStateComponent } from '../../../shared/states/empty-state.component';
import { ErrorStateComponent } from '../../../shared/states/error-state.component';
import { LoadingStateComponent } from '../../../shared/states/loading-state.component';
import { statusPresentation } from '../../../shared/status-presentation';

type CaseListRow = CaseSummary & { latestStatus: string };

@Component({
  selector: 'app-case-list',
  imports: [
    SdButton,
    SdInput,
    CoreFormAccessibilityDirective,
    SdSection,
    SdTable,
    SdPageComponent,
    EmptyStateComponent,
    ErrorStateComponent,
    LoadingStateComponent,
  ],
  templateUrl: './case-list.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CaseListComponent {
  readonly #api = inject(StartFlowApiService);
  readonly #router = inject(Router);
  readonly table = viewChild<SdTable<CaseListRow>>(SdTable);

  readonly cases = signal<CaseSummary[]>([]);
  readonly query = signal('');
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);

  readonly filteredCases = computed<CaseListRow[]>(() => {
    const normalizedQuery = this.query().trim().toLocaleLowerCase('vi');
    return this.cases()
      .filter((item) =>
        normalizedQuery
          ? `${item.companyName} ${item.registrationNumber}`
              .toLocaleLowerCase('vi')
              .includes(normalizedQuery)
          : true,
      )
      .map((item) => ({
        ...item,
        latestStatus: item.latestRun?.status ?? 'NOT_STARTED',
      }));
  });

  readonly emptyState = computed(() =>
    this.cases().length
      ? {
          title: 'Không tìm thấy hồ sơ phù hợp',
          description: 'Thử một tên doanh nghiệp hoặc mã đăng ký khác.',
          actionLabel: 'Xóa tìm kiếm',
        }
      : {
          title: 'Chưa có hồ sơ',
          description: 'Tạo hồ sơ demo để bắt đầu luồng đánh giá.',
          actionLabel: 'Tạo hồ sơ demo',
        },
  );

  readonly tableOption: SdTableOption<CaseListRow> = {
    type: 'local',
    key: 'startflow.cases.list',
    items: () => this.filteredCases(),
    columns: [
      {
        field: 'companyName',
        title: 'Doanh nghiệp',
        type: 'string',
        minWidth: '240px',
        sortable: true,
        cell: { copiable: true, truncate: { enable: true, type: 'tooltip' } },
        click: (_, row) => this.openCase(row),
      },
      {
        field: 'registrationNumber',
        title: 'Mã đăng ký',
        type: 'string',
        width: '160px',
        sortable: true,
        cell: { copiable: true },
      },
      {
        field: 'requestedAmount',
        title: 'Số tiền đề nghị',
        type: 'number',
        width: '180px',
        align: 'right',
        transform: (value) => formatCurrency(Number(value)),
      },
      {
        field: 'latestStatus',
        title: 'Trạng thái',
        type: 'string',
        width: '180px',
        useBadge: (value) => {
          if (value === 'NOT_STARTED') {
            return { type: 'round', color: 'secondary', title: 'Chưa đánh giá' };
          }
          const presentation = statusPresentation(String(value));
          return { type: 'round', color: presentation.color, title: presentation.label };
        },
      },
      {
        field: 'runCount',
        title: 'Số lượt chạy',
        type: 'number',
        width: '120px',
        align: 'right',
      },
      {
        field: 'createdAt',
        title: 'Ngày tạo',
        type: 'string',
        width: '160px',
        transform: (value) => formatDateTime(String(value)),
      },
    ],
    command: {
      align: 'right',
      commands: [
        {
          icon: 'visibility',
          title: 'Xem hồ sơ',
          click: (row) => this.openCase(row),
        },
      ],
    },
    index: { enabled: true, title: 'STT', width: '64px' },
    paginate: { pageSize: 20, pages: [10, 20, 50] },
    sort: { enable: true },
    reload: { visible: true, onReload: () => this.refreshFromTable() },
    config: { visible: true, resizable: true },
    style: { shadow: false },
  };

  constructor() {
    void this.load();
  }

  async load(): Promise<void> {
    this.loading.set(true);
    this.error.set(null);
    try {
      this.cases.set(await this.#api.listCases());
    } catch {
      this.error.set('Không tải được danh sách hồ sơ. Vui lòng kiểm tra kết nối và thử lại.');
    } finally {
      this.loading.set(false);
    }
  }

  async refreshFromTable(): Promise<void> {
    this.error.set(null);
    try {
      this.cases.set(await this.#api.listCases());
    } catch {
      this.error.set('Không tải được danh sách hồ sơ. Vui lòng kiểm tra kết nối và thử lại.');
    }
  }

  updateQuery(value: unknown): void {
    this.query.set(typeof value === 'string' ? value : '');
    queueMicrotask(() => void this.table()?.reload(true, false));
  }

  resetQuery(): void {
    this.updateQuery('');
  }

  handleEmptyAction(): void {
    if (this.cases().length) this.resetQuery();
    else this.createCase();
  }

  createCase(): void {
    void this.#router.navigate(['/cases/new']);
  }

  openCase(item: CaseSummary): void {
    void this.#router.navigate(['/cases', item.id]);
  }
}

<sd-page>
  <div headerLeft class="d-flex flex-column">
    <h1 class="T20M m-0">Hồ sơ doanh nghiệp</h1>
    <p class="T14R text-secondary mt-4 mb-0">
      Tìm kiếm và mở hồ sơ tín dụng demo theo tên doanh nghiệp hoặc mã đăng ký.
    </p>
  </div>
  <sd-button
    headerRight
    autoId="case-list-create"
    type="fill"
    color="primary"
    size="md"
    prefixIcon="add"
    title="Tạo hồ sơ demo"
    (click)="createCase()"
  ></sd-button>

  <sd-section
    title="Danh sách hồ sơ"
    subTitle="Toàn bộ dữ liệu được gắn nhãn DEMO_DATA, không chứa thông tin khách hàng thật."
    icon="folder_open"
  >
    <div class="p-16 pb-0">
      <div class="row justify-content-end">
        <div class="col-12 col-lg-6">
          <sd-input
            autoId="case-search"
            size="sm"
            label="Tìm hồ sơ"
            placeholder="Tên doanh nghiệp hoặc mã đăng ký"
            [model]="query()"
            (modelChange)="updateQuery($event)"
          ></sd-input>
        </div>
      </div>
    </div>

    @if (loading()) {
      <app-loading-state label="Đang tải danh sách hồ sơ…"></app-loading-state>
    } @else if (error()) {
      <div class="p-16">
        <app-error-state
          title="Không tải được hồ sơ"
          [description]="error() ?? ''"
          (retry)="load()"
        ></app-error-state>
      </div>
    } @else if (filteredCases().length === 0) {
      <div class="p-16">
        <app-empty-state
          [title]="emptyState().title"
          [description]="emptyState().description"
          [actionLabel]="emptyState().actionLabel"
          (primaryAction)="handleEmptyAction()"
        ></app-empty-state>
      </div>
    } @else {
      <div class="overflow-x-auto">
        <sd-table autoId="case-list" [option]="tableOption"></sd-table>
      </div>
    }
  </sd-section>
</sd-page>

// frontend/src/features/cases/case-list.tsx
'use client';

import { ArrowRight, Plus, Search } from 'lucide-react';
import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { EmptyState } from '@/src/components/ui/empty-state';
import { ErrorState } from '@/src/components/ui/error-state';
import { LoadingState } from '@/src/components/ui/loading-state';
import { PageHeader } from '@/src/components/ui/page-header';
import { StatusBadge } from '@/src/components/ui/status-badge';
import { formatCurrency, formatDateTime } from '@/src/lib/format';
import type { CaseSummary } from '@/src/lib/models';
import { useStartFlowApi } from '@/src/lib/use-api';

export function CaseList() {
  const api = useStartFlowApi();
  const [items, setItems] = useState<CaseSummary[]>([]);
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => {
    await Promise.resolve();
    setLoading(true);
    setError(null);
    try {
      setItems(await api.listCases());
    } catch {
      setError('Không tải được danh sách hồ sơ.');
    } finally {
      setLoading(false);
    }
  }, [api]);
  useEffect(() => {
    const timeout = window.setTimeout(() => void load(), 0);
    return () => window.clearTimeout(timeout);
  }, [load]);
  const filtered = useMemo(
    () =>
      items.filter((item) =>
        `${item.companyName} ${item.registrationNumber}`
          .toLocaleLowerCase('vi')
          .includes(query.toLocaleLowerCase('vi')),
      ),
    [items, query],
  );

  return (
    <>
      <PageHeader
        eyebrow="Case workspace"
        title="Hồ sơ doanh nghiệp"
        description="Tất cả dữ liệu ở đây đều là DEMO_DATA, không chứa thông tin khách hàng thật."
        actions={
          <Link className="button button--primary" href="/cases/new">
            <Plus aria-hidden="true" /> Tạo hồ sơ demo
          </Link>
        }
      />
      <div className="form-field" style={{ maxWidth: 460, marginBottom: 16 }}>
        <label htmlFor="case-search">Tìm hồ sơ</label>
        <div style={{ position: 'relative' }}>
          <Search
            aria-hidden="true"
            style={{ position: 'absolute', left: 12, top: 12, width: 19 }}
          />
          <input
            className="input"
            id="case-search"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Tên doanh nghiệp hoặc mã đăng ký"
            style={{ paddingLeft: 40 }}
          />
        </div>
      </div>
      {loading ? (
        <LoadingState />
      ) : error ? (
        <ErrorState message={error} onRetry={() => void load()} />
      ) : filtered.length === 0 ? (
        <EmptyState
          title={items.length ? 'Không tìm thấy hồ sơ phù hợp' : 'Chưa có hồ sơ'}
          description={
            items.length
              ? 'Thử tên doanh nghiệp hoặc mã đăng ký khác.'
              : 'Tạo hồ sơ demo để bắt đầu luồng đánh giá.'
          }
          action={items.length ? undefined : { label: 'Tạo hồ sơ demo', href: '/cases/new' }}
        />
      ) : (
        <div className="list-stack">
          {filtered.map((item) => (
            <Link className="panel list-card" href={`/cases/${item.id}`} key={item.id}>
              <div>
                <p className="eyebrow">DEMO_DATA · {item.registrationNumber}</p>
                <h2>{item.companyName}</h2>
                <p className="muted">{item.purpose}</p>
                <div className="inline-meta">
                  <span>{formatCurrency(item.requestedAmount)}</span>
                  <span>{item.runCount ?? (item.latestRun ? 1 : 0)} lượt đánh giá</span>
                  <span>Tạo {formatDateTime(item.createdAt)}</span>
                </div>
              </div>
              <div>
                {item.latestRun ? (
                  <StatusBadge status={item.latestRun.status} />
                ) : (
                  <span className="badge badge--neutral">Chưa đánh giá</span>
                )}
                <ArrowRight aria-hidden="true" style={{ margin: '15px 0 0 auto' }} />
              </div>
            </Link>
          ))}
        </div>
      )}
    </>
  );
}
